import os
from launch import LaunchDescription
from launch_ros.actions import Node
from ament_index_python.packages import get_package_share_directory

def generate_launch_description():
    # Save the RViz config permanently in your workspace
    rviz_config = os.path.expanduser('~/OmnidirectionalPlatform/config/slam_config.rviz')
    
    return LaunchDescription([
        # 1. Joystick Driver (Reads the controller via SDL2 in Docker)
        Node(
            package='joy',
            executable='joy_node',
            name='joy_node',
            parameters=[{'deadzone': 0.05}]
        ),
        
        # 2. RViz2 (Visualizes the map generated by the Orange Pi)
        Node(
            package='rviz2',
            executable='rviz2',
            name='rviz2',
            arguments=['-d', rviz_config]
        ),
        # Teleop Twist Joy (Translates Joystick to Velocity)
		Node(
		    package='teleop_twist_joy',
		    executable='teleop_node',
		    name='teleop_twist_joy_node',
		    parameters=[{
		        'require_enable_button': True,
		        'enable_button': 5, # Right Bumper (RB) on Xbox
		        'axis_linear.x': 1, # Left stick Up/Down
		        'axis_linear.y': 0, # Left stick Left/Right
		        'axis_angular.yaw': 3, # Right stick Left/Right
		        'scale_linear.x': 1.0,
		        'scale_linear.y': 1.0,
		        'scale_angular.yaw': 1.0
		    }],
		    remappings=[('/cmd_vel', '/cmd_vel_joy')]
		),
    ])
